sudo: required
services:
  - docker
language: bash
env:
  global:
    - REGISTRY_USER=praekeltorgdeploy
    - secure: "FR4BFzyhiVe5QKgz1KxnvcKaWVxHuHHl4uA38nio1MymvUtwoEjDzynlGl9eFVs8CLPS9XQZ7E4qin7iXCwyXYip/Gi6pLOPDNWYxb/33oOLPUxDviih9lhmeCzC8Xkvshxuk6L/v4/Hq2+uyFwUP/DiIXWokM1HJ5oz9nU9PznDdlxHyPJQZurT7L0bTIFx8V1kiVVvJlZ9AFkXZAYvg22OhclG9MI6dKypKwHfReYsBICtdkXrWmbyiWluRkuSoXskaw8kmJ8YZJg08r0Uh65jKhnSE2PgIUhl+uVEz3SezPsK2+nTBcW+c6HWNPSJanA/Gx2Jnar0ajSRKFqHudrj1AiwyvCKXmYQbis9Dq/7DUpDYqHiyuqrjyhqy0HnDmFK4o1IEmN2GdzqYBLLGeFnmTQVV8uT7neICdhOYjRQVVBqDbuPAytpxmm5LzEiIHIi4+hueMC8lnb+HvTYlttczVdMo6Bj5yh3CjORSYp98k9gWoQeEsYGse7OOE1oEazWHzdLNZBIqJglrSpLDWc4S8fHKbQW9tK3i9JEuOjBVnGN6rnR9rHROW1ztdl2TadzF+rF4Xrf6ecrQynJ0tczNfvYzTCd10gzpeaLT5K0jUm6qxRu0iNOnfBYf30abKvD3ADgNTZvFTzyYLj7NvKedgsm9wF5y0/xQ0cc6no="
  matrix:
    - APP=go-metrics-api

# Update Docker Engine
before_install:
  - sudo apt-get update
  - sudo apt-get install -qy -o Dpkg::Options::="--force-confold" docker-engine

before_script:
  - IMAGE_TAG="praekeltfoundation/$APP"
  - DOCKERFILE="$APP/Dockerfile"

script:
  - docker build --tag "$IMAGE_TAG" --file "$DOCKERFILE" .
  - $APP/test.sh

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: ./deploy.sh "$IMAGE_TAG"
  on:
    branch: develop
