sudo: required
services:
  - docker
language: bash
env:
  global:
    - REGISTRY_USER=praekeltorgdeploy
    - REGISTRY_PASS=todo
  matrix:
    - APP=go-metrics-api

# Update Docker Engine
before_install:
  - sudo apt-get update
  - sudo apt-get install -qy -o Dpkg::Options::="--force-confold" docker-engine

before_script:
  - IMAGE_TAG="praekeltfoundation/$APP"
  - DOCKERFILE="$APP/Dockerfile"

script:
  - docker build --tag "$IMAGE_TAG" --file "$DOCKERFILE" .
  - $APP/test.sh

after_script:
  - docker images
